### PR TITLE
created 'blm2020' theme, subtheme of Basis, set to default, config export

### PR DESCRIPTION
**Pull request by rick02840**
Setup the basics of sub theme and switched to that them as default (config).

### CODE REVIEW

**Comment by rick02840** [comment]
Note: this branch contains config to set this new blm2020 theme to default.  At this time (8/14 8pm) that theme does not look great.  If that matters, maybe do't merge it yet.

**Comment by rick02840** [comment]
@laryn  Hi Laryn, I working with Geoff on this and started to work on the theme (skin).  Do you have a design / designer?  If not, do you have a site that you like the look of that you would like this site to emulate?  Copy some styling (e.g. fonts) from this?  https://blacklivesmatter.com/chapter/blm-memphis/   Or other site?  Thanks, Rick

**Comment by laryn** [comment]
@rick02840 The most we've got so far is here: https://github.com/Backdrop4Good/blm2020/issues/4

If nobody wanted to work up a design draft I was going to try to pull something together. Do you want to work up a mockup based on the wireframes and the little info we've received so far, or should I, or would you like me to ask for more specific info?

**Comment by laryn** [comment]
PS. Awesome that you and the group are joining in!

**Comment by rick02840** [comment]
@laryn  yes I can do this:  _"work up a mockup based on the wireframes and the little info we've received so far"_.  I will let you know if I have questions.  Thanks! Rick

**Comment by rick02840** [comment]
OK if I merge this PR?

**Comment by laryn** [comment]
Since nothing is live yet and we're starting from scratch here, I don't see a problem with merging it in.

**Pull request merged**
